swiftray release (#336)
* Fix image crop selection rect coordinate transform bug (#140)

* Add moving speed 4800 feedrate

* Fix moving speed (#143)

* Allow importing images with open file button

* Adjust preset manager UI and support change preset

* Support scale lock when directly change spinbox

* Support showing Custom on the presetm

* Add minus icon and fix scale block position bug

* Add dialog title to some ui file

* Fix color blending for image (#149)

* Fix one dimension control point scale lock bug

* Remove the point showing in the middle of bbox

* Hide flux advanced options on doc panel

* Use Swiftray as the only application title

* Fix transform panel and toolbar showing 9999 bug

* Fix 2nd quadrant rotataion reset bug

* Fix rect creation crash bug

* Prevent wrong baud rate and port setting crash

* Refine bitmap raster algorithm (ignore white/transparent background)

* Fix incorrect dpi value

* Fix dpmm settings not apply for preview

* Set dpmm in ctor of ToolpathExporter

* Make indentation aligned

* build-for-windows-clipper-potrace

* Add import boost thread & opencv for Windows

* Build for windows: remove namespace std

* Hide tests

* Fix undefined reference to __imp_WSAXXXX

* Add boost library for MinGW

* Fix std namespace issue

* Refine CMakeLists.txt

* Separate Windows and MacOS config for CMake

Fixup

Fixup

* Let app name start with uppercase

* Fix straight line transform issue

* Hide console window and rename welcome dialog

* Add framing action

* Refine

* Refine

* Enable approach 2

* Fix merge bug

* Drop redundant G1 header to minimize the gcode size

* Fix frame error message issue

* Allow user to open dashboard when running task

* Refine gcode generator

* Implement fast raster print

* Fix alpha data of image missing after crop. (#161)

* Fix remove layer bbox bug

* Fix required time calculation

* Add padding for high speed rastering (default padding: 10mm)

* Support job dashboard pause (#168)

* Discard trailing zero bits

* Fix typo

* Fix gcode-generator reset

* Remove debug message

* Fix misuse of QString indexOf API

* Implement path preview for high speed rastering

* Execute inner path before external path (#170)

* Fix forward rastering and backward ratering line not aligned

* Refine bitmap raster logic and scale canvas based on resolution

* Change execute with play (#172)

* Fix straight line creation bug (#167)

* Accelerate path preview generation by storing multiple lines in one QPainterPath (#174)

* Feature/UI changes (#175)

* Remove job dashboard unused label

* Remove device icon on machines manager

* Set default baudrate 115200

* Support unlock icon and repective dark mode icon

* Add image functions on image panel

* Adjust layout of toolBarConnection

* Adjust machine manager layout

* Adjust jogging panel buttons layout

* Add LazerVida parameters (#157)

* Change fit icon (#176)

* Fix Windows job preview black background (#179)

* Feature/Add minor changes (#180)

* Change laser button to be checkable

* Update README.md

* Add scale lock to transform toolbar (#177)

* Fix width 9999 bug (#178)

* Bug/Rotation Issues (#160)

* Restrict rotation degree in the range 0 to 360

* Fix rotation handler issue

* Prefer to initialize data member in class declaration instead of constructor

* Refactor job controller

* Fix incorrect engraving estimate time

* Remove unused code. Show message box when grbl alarm detected.

* Separate serial port class implementation for MacOS and Winsows system.

* Support data-name in the svg tag (#182)

* Fix invalid baudrate

* Fix machine manager broken layout (#185)

* Handle serial port unplugged

* Handle unplugged serial port for Windows

* Add default machines and remove earth (#184)

* Filled shapes united when display (#186)

* Set 5W as default preset (#189)

* Add icon to welcome dialog (#188)

* Select current machine when opening MachineManager (#181)

* Bug/Fix serial port bug (#187)

* Fix serial port bug

* Fixup

Co-authored-by: Jason Shiao <b01901105@ntu.edu.tw>

* Change LazerVida to Lazervida (#191)

* Show layer dock as left default dock (#190)

* Set classic ui as default (#192)

* Support different origin on Jogging Panel (#194)

* Change laser testing power to 2 percents (#193)

* Manually close serial port before closing application (#196)

* Refactor swiftray.pro file (#198)

* Set cursor to be cross cursor when drawing (#197)

* Use grbl's Jogging state for jogging panel (#195)

* Feature/Add translation (#199)

* Refactor swiftray.pro file

* update translations

* release new translations

Co-authored-by: Net Tseng <b02901184@ntu.edu.tw>
Co-authored-by: jack00770066 <45539597+jack00770066@users.noreply.github.com>

* Fix missing implementation for generator (#201)

* Fix elapsed time not updated in job dashboard (#202)

* Fix jogging panel commans mismatch bug (#203)

* Keep doc and params panel selecting same preset (#200)

* Fix svg import crash bug (#204)

* Fix parameters typo (#206)

* Fix middle button bug and improve coding style (#205)

* Add icon (#208)

* Fix jogging panel moving to edge bug (#207)

* Select on click inside shapes of FillLine layer type (#209)

* Add a name to name machine (#211)

* Update translation of translation message box (#210)

* Fix HFlip icon name (#212)

* Fix translation typo (#214)

* Bug/Wrong layer visible state when selecting layer (#213)

Fix layer setting visible when select layer

* Set workaround for windows crash issue (#215)

Co-authored-by: Jason Shiao <jason@flux3dp.com>

* Fix bug of layer parameter index go to custom when switch layer (#216)

* Fix the preset sync issue between doc panel and param panel (#217)

* Change editSelectAll to chose with hiden or not & loadSVG to only select new layer (#221)

* Fix bug of after delete layer without active layer (#222)

* To remove FPS & Frames (#223)

* Bug/device control protect (#224)

* To sync action between gcode player and job dashboard when click start

* lock jogging panel and actionPreview when gcode player or job dashboard is busy

* Check control enable before sendJob

* In alarm state can't control device

* Fix disable item to framing

* Add bool to sync job dashboard panel exist by connect finished

* Feature/Add GitHub action (#220)

* Add macOS build

* Add win64 mingw build.

* fix incorrect path

* Add notarize and staple

* To protect gcode play enable when gcode isn't empty (#225)

* To control txt function separate

* Draw border for preview working area (#226)

* Update pt size when select multiple type

* Change layer params panel when only one layer (#218)

* Change layer params panel when only one layer

* Change moving tool enable/disable when layer one or more

* Bug/change dark icon (#233)

* Update dark icon image

* Update subtract icon for dark

* Fix the image size to 128*128

* Change classic UI (#234)

* Check the layer is active and the layer to delete (#228)

* Change framing set enable api for device running (#227)

* Fix bug when transformChanged trigger to blockSignals for UI update (#235)

* Rename the parameter

* Bug/fix machine manager add new machine (#232)

* Update machine manager add name as New Machine

* Check machine number to enable remove or not

* Fix minor issue

Co-authored-by: Net Tseng <b02901184@ntu.edu.tw>

* Add speed mode change in prefernece window (#236)

* Add diode laser description to preset name (#237)

* Feature/update preference info (#238)

* Update preference info

* Change preference UI

* Feature/add shift control line and move (#239)

* Add feature for painting line with shift btn control

* Fix bug to paint line when release mouse

* Add feature to move shpae with direction lock when pressing shift

* Add feature to path draw when press shift

* Load image plus icon for dark/normal mode (#240)

* Update icon image in 2022_0628 (#241)

* Bug/preset custom define change (#242)

* Define preset setting custom to -1 for preset power change

* Update check item

* Fix bug update font in TextDrawing mode (#243)

* create PR template

* Bug/transform import image unit form pixel to mm (#245)

* Fix copy layer without parameter settings

* Update classicUI for panel document hight

* Add apply scale after import image or svg

* Bug/UI tuning and layer copy (#244)

* Fix copy layer without parameter settings

* Update classicUI for panel document hight

* Feature/add about window (#249)

* Add about window in testing

* Update about UI wait swiftray text

* Add about icon

* add image for dark mode

* Turing UI

* Change line hight of text

* Feature/remove special port name (#247)

* Fix copy layer without parameter settings

* Update classicUI for panel document hight

* Add apply scale after import image or svg

* Remove the port name cu. or tty.Bluetooth

* Add version info for windwos executable (#250)

Co-authored-by: Jason Shiao <jason@flux3dp.com>

* Fix bug of crash when add layer more then 18 (#252)

* Fix bug of crash when add layer more then 18

* Use QList for layer colors list

Co-authored-by: Jau-Shiuan(Jason) Shiao <b01901105@ntu.edu.tw>

* Feature/add exmaple for user (#251)

* Add example for swiftray

* Add translation for example

* Update example to qml

Co-authored-by: Jau-Shiuan(Jason) Shiao <b01901105@ntu.edu.tw>

* Feature/adjust about window (#254)

* Adjust version number to 1.0.0b

* Adjust about window style

* Fix version suffix

* Change from b to _beta for version suffix

* Add version string for Cmake build

Co-authored-by: Jason Shiao <jason@flux3dp.com>

* Fix missing unicode/ucnv.h (#255)

* Bug/beta version tuning 20220706 (#256)

* Version name change, about UI update & switch file of example(Cutting)

* Remove the menu of machine

* Add initial value for rect, oval and polygon shape

* Update example file, change cmake, and update save file with non select

* Add separated line for menu

* Feature/check machine lazervida to set speed mode (#257)

* Add switch speed mode when select Lazervida

* Replace example file and add disable group in edit

* change about UI text font

* Update translation of speed optimization in about window

* Beta version to 1.0.0-beta01 (#259)

* beta naming rule change (#260)

* Fix bug text control crash when edit without text & keep line height info in canvas (#261)

* Fix bug of string compare with string size too small (#263)

* Bug/add mutex for container (#264)

* Add mutex lock for list update

* Add mutex for Qlist which is class member variable

* Add include file (#265)

* Change opencv lib folder (#266)

* Feature/Remove padding when framing (#267)

* Ignore path with 0% power for dirty area calculation

* Add padding option for toolpath exporter

* Assert feedrate value > 0 when estimating time

* Add start job progress dialog (#268)

* Add start job progress dialog

* Add progress dialog for toolpath export process

* Add translations

Co-authored-by: GaryChunChiaChiu <gary@flux3dp.com>

* Add start in menu (#271)

Co-authored-by: Jau-Shiuan(Jason) Shiao <b01901105@ntu.edu.tw>

* Improve performance of calcRequiredTime() (#272)

* Feature/add check saved before close (#270)

* Add status check for window close

* Add check file status when clear

* Add translation

* Change button for translation

* after check the ts file

* Fix color picker button cancel bug (#273)

* update version for next release (#274)

* Fix incorrect image dithering (#275)

* Feature/paste position with click right button (#276)

* Add point for clicking paste, but still to check the translate distance

* Calculate center and remeber the click when right click

* Change windows setting from essentia to classic (#278)

* remove fill+line layer setting (#279)

* Separate the shift change for scale and direction lock (#277)

Co-authored-by: Jau-Shiuan(Jason) Shiao <b01901105@ntu.edu.tw>

* Bug/change windows font to open sans (#283)

* Change font to Open Sans in windows

* Add font file

* update font size

* Remove the font setting for windows to update

* Change jogging panel text size

* Feature/update windows title when file state change (#282)

* Update windows title when file change

* Add translation

* Add setWindowModified to update mac title icon

* Remove the title hiden and color setting

* Update translation file

* Update translation file

Co-authored-by: Jason Shiao <b01901105@ntu.edu.tw>

* Update image unit without transition pixel to cm (#285)

* Send index changed when preset change(when index = 0 setCurrentIndex don't send changed) (#284)

* Update README.md (#289)

* Update README.md (#290)

* Update jog dashboard status text (#286)

* Add cursor changed for shape detected (#291)

* Ckeck layer lock when double click (#288)

* Add handling for pause by accelerometer sensor (#292)

* Add initial to scale locked (#295)

* version update to next beta.5 (#293)

* Add drag and drop file to canvas (#294)

* Fix job dashboard overlayed by progress dialog (#296)

* Fix job dashboard overlayed by progress dialog

* Remove unused header

* Feature/text cursor control by mouse (#298)

* still checking the position calculate

* Add cursor calculate and set cursor when text control

* Increase the judge range

* Add mouse move and text select function

* Set larger max size for about window (#301)

* Update path string for windows (#302)

* Update cmake boost folder for windows (#303)

* Update version to beta.6 (#304)

* Feature/change layer power and speed to double (#306)

* change layer speed and power to double

* Add error message when the bb file version overrange

* Update cursor change rule to update cursor shape only once (#307)

* Add crash report for sentry (#300)

* Add Mac M1 .pro setting

* Refine CMake

* Refine cmake

* Refine cmake

* Add sentry for macOS

* Add install() command for bundle

* Add cmake build workflow for macOS

* fix

* fix

* try

* Create dmg for cmake macOS build

* Update sentry dsn

* Add sentry project release version

* Add codesign for crashpad_handler

* Try upload dSYM to sentry

* Fix

* fix

* Use absolute path for crashpad_handler

* Support msvc build

* Adjust CMake and QMake for Windows

MSVC and Mingw build

* Add crashpad and sentry for msvc

Fix

Refine cmake and qmake

Enable sentry for Windows

Add potrace search path

* Fix app icon for windows not applied

* Fix boost library linking

* Link sentry lib for macOS qmake build

* Add Apple Silicon qmake build

* Change from qmake to cmake for macOS release build

* Fix cmake build GUI instead of console for MSVC2019

* Change cmake build type from debug to relwithdebinfo

* Refine

* Refine macOS cmake build workflow

* Add QMAKE_RPATHDIR for Mac build

* Import sentry-native as submodule

* Fix github action for submodule

* Move crashpad_handler to MacOS folder. Sign crashpad_handler

* Fix cmake install path

* Update README.md

* Refine github build workflow

* fix

Fix macOS workflow bug

* Change release build workflow name

* Update README.md

Co-authored-by: GaryChunChiaChiu <gary@flux3dp.com>
Co-authored-by: Jason Shiao <jason@flux3dp.com>
Co-authored-by: Dean Sung <dean@flux3dp.com>
Co-authored-by: GaryChunChiaChiu <106943724+GaryChunChiaChiu@users.noreply.github.com>

* Add read dxf file (#308)

* Add cursor position calculate for space (#309)

* Feature/update toolbar (#305)

* Update toolbar name

* Add panel & toolbar select in window menu

* Feature/add UI performance tuning (#310)

* Change canvas zoom in step and min

* add setting UI font size

* try to update the font size

* Fix the chinese display & some translation update (#311)

* upadte lazervida working range (#316)

* Update README.md (#314)

* version update to beta7 (#313)

* Update font size for windows display (#315)

* Feature/add holding ctrl in preview (#312)

* Add holding ctrl

* Add holding ctrl & wheel to zoom preview UI

* Send G90 to force absolute positioning for framing (#318)

* Feature/adjust app description (#317)

* Update CMakeLists.txt

Add definitions for Windows app version

* Update win.rc

* Update CMakeLists.txt

* Update CMakeLists.txt

* Update swiftray.pro

* Change MacOS bundle info in CMakeLists.txt

* Feature/add privacy setting (#319)

* feature/add-privacy-setting

* try to free sentry when upload disable

* remove no used function

* change upload enable by set consent

* read upload by qsettings

* reopen qxcopeguard

* relocate sentry data folder

* version update ,change sentry folder location, and change privacy show after welcome (#321)

* Feature/updata git file (#322)

* Move style, font, and images to resources

* remove file not using

* Update README.md

* Feature/refine cmake (#323)

* Refine CMakeLists.txt

* Use target_sources() in CMakeLists.txt

* modify the current PR template

* Hide README of svg parser (#331)

* Update README.md (#327)

* Add define ENABLE_SENTRY for user to give dsn (#332)

* Add define ENABLE_SENTRY for user to give dsn

* Update main.cpp

* Update mainwindow.cpp

Co-authored-by: Jau-Shiuan(Jason) Shiao <b01901105@ntu.edu.tw>

* Update CMakeLists.txt for sentry option (#333)

* Add direction control by 45 degrees (#324)

* Update build-release.yml

* Change wheel control to update scale only (#326)

* Update build-release.yml

* Bug/fix release build workflow (#334)

* Try fix py7zr install fail

* Fix gcc version

* FIXUP

* FIXUP

Co-authored-by: GaryChunChiaChiu <106943724+GaryChunChiaChiu@users.noreply.github.com>

* Update win64 & cmake(linux) build by workflow_dispatch (#335)

* Add drop file for .dxf (#325)

* Feature/add boundary for generated path (#320)

* Add boundary for generated path.

* Set default machine work area to canvas size when no machine settings exists.

* Add warning popup for items not placed fully inside the working area

* Fix transform bug

* Add translations

Co-authored-by: GaryChunChiaChiu <gary@flux3dp.com>

* Update build-release.yml

Co-authored-by: Jau-Shiuan(Jason) Shiao <b01901105@ntu.edu.tw>
Co-authored-by: Net Tseng <b02901184@ntu.edu.tw>
Co-authored-by: Jason Shiao <jason@flux3dp.com>
Co-authored-by: jack00770066 <45539597+jack00770066@users.noreply.github.com>
Co-authored-by: Yanting Chen <mx.alexender@gmail.com>
Co-authored-by: Yanting Chen <ChenYanting@users.noreply.github.com>
Co-authored-by: Dean Sung <dean@flux3dp.com>